spring:
  datasource:
    url: jdbc:mysql://10.36.2.128:3306/jht_feature_2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: zhangxu  #用户名
    password: 1QAZ2wsx$  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

version: /v1

mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*Dao.xml

logging:
   config: F:/workspace-springboot/jht/api-server/src/main/resources/logback.xml
   level:
     com.hjt: debug